"""
Learning Protocol Loader for QuantraCore Apex.

Learning protocols generate labels for ApexLab training.
"""

from typing import Dict, Any, List, Optional
from dataclasses import dataclass
import importlib
import logging

from src.quantracore_apex.core.schemas import OhlcvWindow, ApexResult


logger = logging.getLogger(__name__)


@dataclass
class LearningLabel:
    """A label generated by a learning protocol."""
    protocol_id: str
    label_name: str
    value: Any
    confidence: float
    metadata: Dict[str, Any]


class LearningProtocolRunner:
    """
    Runs learning protocols to generate teacher labels.
    """
    
    def __init__(self):
        self.protocols: Dict[str, Any] = {}
        self._load_protocols()
    
    def _load_protocols(self) -> None:
        """Load all LP01-LP25 protocol modules."""
        for i in range(1, 26):
            protocol_id = f"LP{i:02d}"
            module_name = f"src.quantracore_apex.protocols.learning.{protocol_id}"
            
            try:
                module = importlib.import_module(module_name)
                if hasattr(module, "generate_label"):
                    self.protocols[protocol_id] = module.generate_label
                    logger.debug(f"Loaded learning protocol {protocol_id}")
            except ImportError:
                pass
    
    def run_single(
        self,
        protocol_id: str,
        window: OhlcvWindow,
        apex_result: ApexResult
    ) -> Optional[LearningLabel]:
        """Run a single learning protocol."""
        if protocol_id not in self.protocols:
            return None
        
        try:
            return self.protocols[protocol_id](window, apex_result)
        except Exception as e:
            logger.error(f"Error running learning protocol {protocol_id}: {e}")
            return None
    
    def generate_all_labels(
        self,
        window: OhlcvWindow,
        apex_result: ApexResult
    ) -> List[LearningLabel]:
        """Generate all labels for a window."""
        labels = []
        
        for i in range(1, 26):
            protocol_id = f"LP{i:02d}"
            label = self.run_single(protocol_id, window, apex_result)
            if label:
                labels.append(label)
        
        return labels
    
    def to_label_dict(self, labels: List[LearningLabel]) -> Dict[str, Any]:
        """Convert labels to a flat dictionary."""
        return {
            label.label_name: label.value
            for label in labels
        }
