#!/usr/bin/env python3
"""
TURBO EXPAND - Efficient stock fetching and training
- Parallel feature extraction (8 workers)
- Larger API batches (100 symbols)
- Feature caching to skip recomputation
- Vectorized numpy operations
"""
import os
import sys
import time
import pickle
import gzip
import hashlib
from datetime import datetime, timedelta
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
import requests
import pandas as pd
import numpy as np
from sklearn.metrics import precision_score, recall_score, roc_auc_score
import lightgbm as lgb

ALPACA_DATA_URL = 'https://data.alpaca.markets'
CACHE_DIR = Path('data/cache/polygon/day')
MODELS_DIR = Path('data/models')
FEATURE_CACHE = Path('data/cache/features')
CACHE_DIR.mkdir(parents=True, exist_ok=True)
FEATURE_CACHE.mkdir(parents=True, exist_ok=True)

HEADERS = {
    'APCA-API-KEY-ID': os.environ.get('ALPACA_PAPER_API_KEY', ''),
    'APCA-API-SECRET-KEY': os.environ.get('ALPACA_PAPER_API_SECRET', '')
}

SYMBOL_POOLS = [
    'AAL AAPL AAWW ABBV ABC ABCL ABCM ABNB ABR ABSI ABUS ACAD ACCD ACDC ACGL ACHC',
    'ACIW ACLS ACMR ACNB ACR ACRX ACRV ACTG ADAP ADBE ADC ADEA ADER ADGI ADMA ADM',
    'ADP ADSK ADT ADTN ADTX ADUS ADV ADVM AEHR AEIS AEL AEM AENT AENZ AERI AES AEVA',
    'AFCG AFDG AFIB AFMD AFRI AFYA AG AGBA AGCO AGFY AGIO AGLY AGM AGNC AGO AGRI AGS',
    'AGTI AGYS AHCO AHG AHH AHPI AHR AI AIB AIG AIMD AIMH AINC AIR AIRE AIRG AIRT',
    'AIT AIV AIZ AJAX AJRD AJX AKAM AKBA AKLI AKRO AKTS AKYA AL ALAC ALAR ALB ALBT',
    'ALC ALCC ALDX ALE ALEC ALEX ALG ALGM ALGN ALGS ALGT ALHC ALIM ALIT ALK ALKS',
    'ALKT ALL ALLE ALLG ALLK ALLO ALLY ALNY ALOG ALOT ALPP ALPS ALRS ALRM ALSA ALT',
    'ALTA ALTG ALTL ALTO ALTR ALTS ALV ALVO ALXO ALYA ALZN AM AMAL AMAT AMBA AMBC',
    'AMBO AMBP AMCR AMCX AMD AME AMED AMEH AMG AMGN AMH AMK AMKR AMLI AMLX AMN AMNB',
    'AMOT AMOV AMP AMPE AMPG AMPH AMPL AMPS AMPY AMR AMRC AMRK AMRN AMRX AMS AMSC',
    'AMSF AMST AMT AMTB AMTD AMTX AMWD AMWL AMY AMZN AN ANAB ANDR ANF ANGI ANGN ANGS',
    'ANIK ANIP ANIX ANN ANNX ANSS ANT ANTE ANVS ANY AON AORT AOS AOSL AOSP AOUT AP',
    'APA APAM APCA APD APE APEI APG APGE APH API APLD APLE APLS APLT APM APOG APP',
    'APPF APPN APPS APRE APRN APTO APTV APVO APWC APXI APYX AQB AQMS AQN AQST AQUA',
    'AR ARC ARCB ARCH ARCO ARCT ARDX ARE AREN ARES ARGT ARGX ARHS ARI ARIA ARIC ARIS',
    'ARKK ARKO ARKR ARL ARLP ARMK ARMN ARMP ARNC ARNG AROC AROW ARQT ARRY ARSN ART',
    'ARTH ARTL ARTNA ARTW ARVN ARWR ARY ARYA ASA ASAI ASAN ASAX ASB ASCA ASGN ASH',
    'ASIX ASLE ASLN ASM ASMB ASML ASND ASO ASPA ASPI ASPS ASPZ ASRT ASRV AST ASTE',
    'ASTS ASTX ASUR ASXC ASYS AT ATA ATAI ATAT ATAX ATCO ATCX ATEC ATEK ATEN ATER',
    'ATEX ATFV ATHM ATIF ATKR ATLC ATLO ATMC ATMU ATNF ATNI ATNX ATO ATOM ATOS ATRA',
    'ATRC ATRI ATRO ATSC ATSG ATTO ATUS ATVI ATXI ATXS AU AUB AUBN AUDC AUDD AUGX',
    'AUID AUMN AUPH AURA AURB AURC AURI AUTO AUVI AUY AUXO AVAH AVAL AVAV AVCO AVD',
    'AVDL AVDX AVE AVGO AVGR AVID AVIR AVNS AVNT AVNW AVO AVPT AVRO AVT AVTA AVTE',
    'AVTX AVTR AVXL AVY AVYA AWH AWI AWK AWLZ AWON AWR AWRE AWSM AX AXAS AXDX AXGN',
    'AXIL AXIM AXLA AXNX AXON AXP AXR AXS AXSM AXT AXTI AXU AY AYI AYLA AYRO AYTU',
    'AYX AZ AZA AZEK AZN AZO AZPN AZRE AZTA AZZ B BA BABA BAC BAH BALL BANC BAND',
    'BANF BANR BAOS BAP BARK BASE BATL BATRA BATRK BAX BB BBAI BBAX BBAR BBCP BBDC',
    'BBDO BBGI BBIG BBIO BBN BBSI BBTX BBU BBUC BBVA BBWI BBY BC BCAB BCAN BCBP BCC',
    'BCDA BCDAW BCE BCEL BCEI BCH BCLI BCML BCNC BCO BCOV BCOW BCRX BCSA BCSF BCX',
    'BCYC BDC BDCX BDGS BDMD BDN BDSI BDSX BDTX BDX BE BEAM BEAT BECN BEL BEKE BELFB',
    'BEN BENF BENN BEPC BEPH BEPI BERN BERW BEST BETZ BF BFC BFAM BFC BFI BFIN BFLY',
    'BFRI BFS BFST BFX BG BGB BGC BGCP BGFV BGH BGI BGNE BGRY BGS BGSF BHAT BHB BHC',
    'BHE BHF BHG BHLB BHRB BHR BHVN BIDU BIG BIGB BIGC BIIB BILI BILL BIMI BIMINI',
    'BIOC BIOL BIOS BIOT BIOX BIRD BIS BITE BITF BIVI BJ BJDX BJRI BK BKCC BKCH',
    'BKD BKE BKH BKKT BKNG BKR BKSY BKTI BKU BL BLAC BLBD BLBX BLCM BLCO BLD BLDP',
    'BLDR BLEU BLFS BLFY BLI BLIN BLKB BLL BLMN BLND BLNG BLNK BLPH BLRX BLSA BLTE',
    'BLUE BLV BLVN BLZE BMA BMAC BMAP BMBM BMBL BMI BMRC BMRE BMRN BMTX BMY BNCAT',
    'BNE BNED BNET BNFT BNGN BNNR BNO BNOX BNR BNRE BNTC BNTX BNYM BOC BOCN BOD',
    'BODY BOF BOJA BOKF BOLT BOLT BOMN BOOM BOOT BORR BOSC BOTJ BOWL BOX BOXL BPMC',
    'BPMX BPOP BPRN BPTH BPY BPYU BQ BR BRAG BRBR BRBS BRC BRCC BRDG BREA BRES BRFS',
    'BRG BRGR BRHI BRID BRIO BRIT BRIX BRIV BRKA BRKL BRKN BRKR BRKS BRLC BRLT BRM',
    'BRMK BRMN BRNS BRO BROG BROS BRP BRPM BRRR BRSH BRSP BRT BRTX BRW BRWC BRX BRY',
    'BRZE BSAC BSBK BSBR BSET BSGM BSIG BSLK BSM BSMX BSQR BSRR BSRX BSSE BSSX BSTC',
    'BSTZ BSV BSVN BSX BSYT BTA BTAI BTB BTBD BTBT BTCM BTCS BTCY BTDR BTG BTI BTMD',
    'BTN BTOG BTR BTRS BTT BTU BTTX BTXX BTZ BURL BUSE BVFL BVN BVNRY BVS BVXV BW',
    'BWA BWAC BWAY BWB BWBBP BWE BWL BWMN BWMX BWV BWXT BX BXC BXMT BXP BY BYD BYFC',
    'BYND BYRN BYSI BYTS BZ BZFD BZH BZUN C CAAS CABA CABO CAC CACI CADE CADL CAE',
    'CAG CAH CAKE CAL CALB CALC CALM CALX CAMP CAMS CANB CANG CAPL CAPR CAPX CAR',
    'CARA CARE CARG CARM CARR CARS CARV CAS CASI CASS CASY CAT CATC CATO CATY CB',
    'CBAN CBAT CBAY CBFV CBH CBIO CBIT CBL CBNA CBOE CBRE CBRL CBSH CBT CBU CBUS CBZ',
    'CC CCAP CCB CCBG CCBI CCCC CCCO CCCS CCD CCEL CCEP CCHR CCI CCIV CCJ CCLK CCL',
    'CCLD CCMP CCNC CCNE CCNEP CCO CCOI CCOIX CCOR CCRB CCRN CCS CCSI CCTG CCU CCUR',
    'CCV CCVH CCVI CCX CCXI CD CDAY CDBM CDIO CDLX CDMO CDNA CDNS CDNS CDR CDRE',
    'CDRO CDTI CDTX CDW CDXC CDXS CDZI CDZIP CE CEA CECE CECO CEG CEI CELC CELH CELU',
    'CELZ CEM CEMP CENN CENT CENTA CENX CEO CEPU CEQP CERE CERN CERT CERS CETX CETXW',
    'CEVA CF CFA CFB CFBK CFCV CFG CFFS CFFN CFII CFIV CFLT CFR CFRX CFSB CFVI CG',
    'CGA CGAU CGBD CGC CGEM CGEN CGMS CGON CGRO CHAA CHCI CHCO CHCT CHDN CHE CHEA',
    'CHEF CHEK CHGG CHGX CHH CHK CHKP CHKR CHL CHMA CHMG CHMI CHN CHNC CHNR CHPT',
    'CHRB CHRD CHRS CHRW CHS CHT CHTR CHUY CHW CHWY CHX CHY CI CIBR CIEN CIFR CIG',
    'CIGI CIH CIIG CIK CIM CINF CING CINT CIO CIR CISO CIT CITE CIVB CIVI CIVS CIX',
    'CIZN CJJD CKH CKPT CKX CL CLAR CLAQ CLAR CLAX CLAY CLB CLBK CLBR CLBT CLCO CLCT',
    'CLDX CLDT CLEN CLEU CLFD CLGN CLGX CLH CLIR CLLS CLLS CLMB CLN CLNE CLNN CLOV',
    'CLPR CLPS CLPT CLR CLRB CLRG CLRO CLRS CLS CLSD CLSK CLSN CLST CLSTR CLW CLWT',
    'CLX CLXT CLYM CLZR CM CMA CMBS CMC CMCM CMCO CMCSA CMD CME CMG CMI CMLF CMLS',
    'CMM CMNB CMP CMPI CMPO CMPR CMPS CMRA CMRE CMRX CMS CMSA CMT CMTG CMTL CMU CNA',
    'CNAK CNC CNCE CNDA CNET CNF CNFR CNHI CNI CNK CNMD CNNB CNNE CNOB CNOBP CNO',
    'CNPN CNPP CNQ CNR CNRG CNSL CNSP CNTA CNTB CNTY CNVS CNVY CNXC CNXN CNY CO',
    'COAL COAT COCH COCO COCP CODA CODE CODI CODX COE COF COGT COHU COIN COIV COKE',
    'COLB COLD COLI COLM COMM COMP CONN COO COOP COP COPR COPX COR CORD CORE CORG',
    'CORR CORS CORT COSM COST COTY COUP COUR COWN CP CPA CPB CPE CPF CPG CPHI CPK',
    'CPLG CPLP CPNG CPOP CPRI CPRX CPSH CPSI CPSS CPST CPT CPTA CPTN CPZ CQQQ CR',
    'CRAI CRBG CRBU CRCO CRCT CRCW CRD CRDA CRDF CRDL CRDO CREE CREG CRESY CREW CREX',
    'CRF CRFG CRGE CRGI CRGO CRGS CRH CRHC CRHM CRIS CRK CRKN CRMD CRMT CRNC CRNT',
    'CRNX CRON CROX CRPO CRPU CRQI CRRCU CRSA CRSP CRSR CRST CRT CRTD CRTM CRTO CRTX',
    'CRUS CRVL CRVS CRWD CRWS CRWS CRY CS CSAN CSBR CSCO CSCW CSGP CSGS CSII CSIQ',
    'CSIW CSLT CSLX CSMT CSP CSPI CSQ CSRA CSSE CSTE CSTL CSTM CSTR CSTU CSV CSWC',
    'CSWI CSX CTA CTAQ CTAS CTB CTBI CTDD CTG CTGO CTHR CTIB CTIC CTLP CTLT CTMX CTO',
    'CTOS CTRA CTRE CTRM CTRN CTRO CTRS CTSH CTSO CTT CTTC CTVA CTXR CTXS CTV CTVA',
    'CUB CUBE CUBB CUBI CUE CUK CULL CULP CURI CURO CURV CUTR CUYK CVAC CVBF CVC',
    'CVCO CVCY CVE CVEO CVET CVGI CVGW CVII CVIM CVKD CVLC CVLG CVLT CVLY CVNA CVO',
    'CVRX CVS CVT CVU CVV CVX CW CWAC CWBC CWBHF CWBK CWBR CWCO CWD CWEB CWH CWK',
    'CWST CWT CX CXA CXAI CXE CXM CXP CXW CXSE CYAD CYBC CYBN CYBR CYCC CYD CYDY',
    'CYH CYN CYRN CYT CYTK CYTO CZFS CZNC CZOO CZR CZWI D DAC DADA DAIO DAKT DAL',
    'DALY DAN DANA DAOO DAR DARE DART DASH DATS DAVA DAVE DAWN DB DBA DBGI DBI DBL',
    'DBRG DBTX DBVT DBX DC DCBO DCFC DCGO DCO DCOM DCPH DCRD DCS DCUE DDC DDD DDF',
    'DDI DDIV DDL DDMX DDOC DDS DDT DE DEA DECK DEFI DELL DENN DEO DESP DES DEX',
    'DFFN DFIN DFJ DFLI DFN DFNL DFPH DFS DG DGHI DGICA DGICB DGII DGLY DGNR DGNS',
    'DGS DGT DGTI DGX DHC DHF DHIL DHI DHR DHS DHT DIAL DIC DIFF DIFO DIN DINO DIOD',
    'DIS DISA DISCA DISCB DISCK DISH DIST DIT DJCO DK DKNG DL DLA DLCA DLO DLR DLTH',
    'DLTR DLX DM DMA DMAC DMAQ DMB DMDV DMF DMLP DMRC DMTK DNA DNAA DNAB DNAC DNAD',
    'DNAN DNAY DNB DNKN DNLI DNMR DNN DNP DNPTP DNRSF DNUT DNZ DO DOC DOCU DOGZ DOLE',
    'DOMO DOOO DOOR DORM DOV DOXA DOYU DPG DPL DPM DPS DPSI DPST DPZ DQ DRCT DRDGF',
    'DRE DRH DRIP DRIV DRMB DRNA DRNH DRQ DRS DRTS DRTT DRVN DS DSCR DSDDF DSEY DSGN',
    'DSGR DSGX DSKE DSL DSLV DSM DSN DSNY DSP DSPR DSS DSSI DSTL DSU DSWL DSX DT',
    'DTC DTE DTF DTG DTIL DTM DTOC DTRK DTSS DTST DTV DTVV DUK DUNE DUO DUOL DUPA',
    'DUR DUSL DUSS DVAX DVD DVMT DVN DVYA DWA DWAC DWAS DWCH DWL DWLD DWM DWN DWSH',
    'DWX DX DXC DXCM DXF DXJ DXLG DXPE DXPS DXR DXYN DY DYN DYNT DZSI E EA EAC',
    'EAD EAF EAR EAT EB EBAY EBIZ EBR EBS EBSB EC ECC ECL ECNS ECOM ECOR ECPG ECVT',
    'ED EDAP EDBL EDIT EDN EDR EDRI EDRY EDSA EDTK EDTX EDUC EDW EE EEFT EFAV EFBI',
    'EFC EFF EFNL EFOI EFSC EFV EFX EG EGAN EGBN EGHT EGIO EGL EGLY EGO EGP EGRX',
    'EGY EH EHC EHI EHLT EHR EHTH EIC EIDO EIG EIGI EIM EIX EL ELA ELAN ELAS ELAT',
    'ELB ELBI ELEV ELF ELGT ELI ELIAF ELIQ ELLO ELMD ELME ELMS ELOX ELP ELS ELTK',
    'ELV ELYA ELYM EM EMBC EMBK EMCF EMD EME EMKR EML EMLD EMLP EMMS EMN EMO EMP',
    'EMPW EMQ EMR EMSG EMTY EMX EMYB ENDP ENER ENFC ENG ENGL ENGN ENGS ENLV ENNV',
    'ENOB ENPH ENOV ENPC ENPHO ENRG ENS ENSC ENSG ENSV ENT ENTA ENTF ENTG ENTI',
    'ENTO ENTR ENTX ENV ENVA ENVB ENVX ENZY EOG EOSE EOSS EP EPAC EPAD EPAM EPAY',
    'EPC EPD EPIX EPP EPR EPRT EPS EPTA EQBK EQC EQFN EQH EQIX EQNR EQR EQS EQT',
    'EQX ERA ERAM ERF ERH ERIC ERIES ERII ERJR ERNZ ERO ERYP ES ESBK ESC ESCA ESCR',
    'ESCR ESEA ESGC ESGD ESGE ESGR ESGS ESGU ESIA ESLA ESLT ESMI ESMT ESNT ESO',
    'ESOA ESP ESPO ESPOV ESPR ESQ ESRT ESS ESSA ESSC ESTC ESTE ET ETE ETG ETH',
    'ETHM ETHO ETJ ETN ETNB ETO ETON ETR ETRI ETRNW ETSW ETSY ETTX ETW ETWO ETX',
    'ETY EU EUBC EUM EURN EUSA EVA EVBG EVBN EVC EVCM EVCP EVE EVER EVEX EVF EVFM',
    'EVG EVGN EVGO EVH EVIX EVK EVLO EVLV EVM EVMT EVN EVO EVOH EVOK EVOP EVRI',
    'EVRN EVRY EVTC EVTL EVTV EVVV EW EWBC EWC EWCZ EWG EWH EWJV EWL EWM EWMF EWN',
    'EWP EWQ EWS EWT EWU EWW EWY EWZ EXAI EXAS EXEL EXFY EXG EXIR EXLS EXPE EXPD',
    'EXPO EXPR EXR EXRX EXTN EXTR EYE EYEG EYEN EYPT EZGO EZPW F FAF FAMI FANG',
    'FANW FAT FATB FATE FATP FAX FAZE FB FBC FBCG FBGX FBHS FBIO FBK FBMS FBNC FBP',
    'FBRT FC FCAP FCBP FCCO FCEL FCFS FCN FCNCA FCPT FCR FCRE FCRX FCS FCSE FCT FCTD',
    'FCX FCZA FD FDBC FDEF FDF FDL FDLO FDM FDML FDN FDP FDS FDUS FDX FE FEAM FEAT',
    'FEIM FELE FELP FELU FEM FEMY FEN FENG FENY FEO FEP FER FERG FERN FET FEUZ FEVR',
    'FF FFA FFBC FFBW FFEB FFHL FFIC FFIE FFIN FFIV FFNT FFNW FFWM FG FGBI FGD FGEN',
    'FGF FGI FGL FGMC FGNA FGP FGRP FH FHB FHI FHLT FHN FHTX FI FICO FICS FIDO FIF',
    'FIFTY FIG FIGS FIHL FINM FINV FINW FIP FIPXX FIRE FISI FISV FIT FITB FITBI',
    'FITBO FITS FIVE FIVN FIW FIX FIXD FIXS FIXX FIZZ FJP FJTC FK FKWL FL FLAG',
    'FLAX FLDM FLEX FLGC FLIC FLIN FLIR FLL FLMX FLNG FLNR FLNT FLO FLOT FLOW FLQM',
    'FLR FLS FLSW FLT FLTX FLUR FLUX FLV FLWS FLXN FLXS FLYA FLYW FLYX FMAO FMB',
    'FMBH FMBI FMED FMG FMHI FMI FMIV FMN FMNB FMO FMS FMST FMT FMTX FMX FN FNA',
    'FNB FNCB FNCH FNCLX FND FNDX FNHC FNKO FNLC FNV FNX FNY FNYE FNZ FO FOCS FOE',
    'FOF FOGO FOLD FOR FORA FORD FORE FORK FORL FORR FOSL FOSLL FOST FOX FOXA FOXF',
    'FPAC FPAY FPE FPEI FPF FPH FPI FPL FPOK FPRX FPRXU FPT FPX FPXI FR FRA FRBA',
    'FRBK FRCB FRD FREE FREEW FREL FREQ FRES FRFHF FRG FRGI FRGR FRGS FRHC FRLA',
    'FRLN FRMA FRME FRMEP FRO FROG FRPH FRPT FRS FRSH FRST FRTX FRV FRW FRXB FRZA',
    'FS FSB FSBW FSCO FSFG FSHP FSI FSK FSKR FSLR FSM FSP FSRX FSS FSSAU FSST FST',
    'FSTB FSTR FSTX FSV FTAI FTC FTCH FTCI FTCS FTDR FTEC FTEK FTEO FTEV FTFT',
    'FTGC FTHI FTI FTII FTK FTNT FTOC FTR FTRI FTS FTSD FTSF FTSL FTSM FTSV FTTEU',
    'FTVIV FTW FTV FTXD FTXG FTXH FTXL FTXN FTXO FTXR FTXZ FUL FULC FULT FUN FUNC',
    'FUND FURI FUSE FUTU FUV FUTR FUV FVAL FVCB FVE FVRR FWONA FWONK FWP FWRD FXB',
    'FXC FXD FXE FXF FXG FXH FXI FXL FXN FXO FXP FXR FXSG FXU FXY FXZ FYBR FYIO',
    'FYT G GA GABC GACQ GAD GAFG GAFL GAIA GAIN GAIS GALT GAM GAMI GANX GAQ GASS',
    'GATO GATX GAU GAW GAWK GBBR GBCI GBDC GBF GBFP GBH GBIL GBIO GBLI GBOX GBNY',
    'GBR GBRI GBRO GBT GBTC GBTG GBX GCAC GCBC GCI GCMG GCMGW GCO GCOM GCR GCTK',
    'GCV GCW GDDY GDL GDNR GDOT GDRX GDS GDT GDTC GDV GDYN GE GECC GECK GEF GEG',
    'GEHI GEL GENC GENE GENI GENK GENO GENY GEO GEOS GERN GES GEST GET GETY GF GFA',
    'GFAI GFED GFF GFI GFL GFLU GFN GFR GFRD GFRK GFX GGB GGAL GGG GGGV GGM GGN',
    'GGP GGR GGT GGTT GGZ GH GHAC GHBS GHC GHG GHIB GHL GHLD GHM GHNG GHP GHRS',
    'GHSI GHY GIB GIFI GIG GIGM GIK GIL GILD GILT GIM GINN GIPPU GIS GISFF GITAX',
    'GITA GIW GKOS GL GLA GLAD GLAQ GLBE GLBR GLBS GLBZ GLC GLCN GLDD GLDG GLDI',
    'GLDX GLGE GLI GLIN GLLI GLLM GLLP GLMD GLNG GLNK GLO GLOB GLOG GLOP GLOW GLP',
    'GLPG GLPI GLRE GLS GLSI GLST GLT GLTO GLTX GLU GLUE GLUU GLVA GLW GLYC GM GMAB',
    'GMACL GMAN GMB GMBC GMBL GMBLZ GMBT GMDA GME GMED GMENQ GMGI GMHG GMI GMM GMND',
    'GMNS GMOM GMP GMRE GMRS GMS GMTX GMW GMY GMZP GNCA GNCAY GNCK GNDI GNDX GNE',
    'GNFT GNGY GNK GNL GNLN GNMA GNNX GNOF GNPX GNRC GNRS GNSS GNST GNSZ GNT GNTA',
    'GNTX GNTY GNUS GNXI GO GOAC GOAI GOAT GOBI GOCO GOED GOEV GOF GOGL GOGO GOLD',
    'GOLF GOOD GOOG GOOGL GOOS GOP GORO GOSS GOTH GOV GOVI GOVX GP GPC GPCR GPEC',
    'GPF GPI GPK GPL GPM GPMT GPN GPOR GPOW GPRE GPRK GPRO GPS GPT GPTC GPU GPX',
    'GQRE GR GRAB GRAI GRAM GRAO GRAZ GRBK GRBKP GRCU GREE GRFS GRFX GRI GRID GRIL',
    'GRIN GRMN GRND GRNH GRNT GROM GRON GROV GROW GRP GRPH GRPN GRPRF GRR GRSH GRSO',
    'GRSV GRTX GRUG GRVI GRVY GRWG GRX GRXS GRY GS GSAH GSAQ GSBC GSBD GSB GSC',
    'GSCR GSEC GSEL GSEU GSEV GSEW GSFP GSHD GSIE GSIG GSJY GSK GSLD GSLN GSLP GSM',
    'GSMG GSMGW GSP GSPM GSPR GSPT GSPY GSQ GSQB GSQD GSS GSSE GSST GSTS GSV GSVC',
    'GSW GSX GSY GT GTA GTAC GTBP GTC GTEC GTES GTHR GTI GTII GTL GTLB GTLL GTLS',
    'GTN GTPA GTPB GTS GTT GTX GTY GUA GUAR GUB GUCK GUD GURE GURU GUT GVA GVBT',
    'GVH GVNC GVP GWAC GWAV GWBL GWB GWEN GWH GWIN GWII GWIX GWPH GWRE GWRS GWR',
    'GWW GXII GXO GYRO H HA HAAC HACK HAE HAFC HAIN HAL HALO HAMP HAPS HASI HAYW',
    'HAR HARP HART HAS HASI HAYN HB HBAN HBANN HBANO HBB HBCP HBD HBI HBIO HBMAW',
    'HBM HBNC HBP HBR HBS HBT HC HCA HCAR HCAT HCCC HCCI HCCW HCC HCDI HCFT HCG',
    'HCHC HCI HCKT HCKT HCM HCNE HCNWW HCP HCSG HCTI HCVI HCXY HD HDB HDC HDFC',
    'HDGE HDS HDTX HDV HDVY HE HEA HEAR HEBT HECO HEDD HELE HELI HELX HENC HENM',
    'HEP HEPA HEPS HERZ HES HESM HEQ HES HESM HEV HEW HEXO HFC HFFG HFGIC HFI HFWA',
    'HG HGBL HGEN HGIF HGNH HGSH HGTY HGV HH HHGR HHLA HHR HHRS HHS HI HI3 HIBB',
    'HIBI HIBS HIDE HIFS HIFW HIG HIGA HIGI HIGT HIHO HII HIIQ HIL HILO HILT HIMR',
    'HIMS HIMX HIVE HIW HIWP HIX HJLI HKIB HKXCY HL HLF HLGE HLI HLIO HLIT HLLY HLM',
    'HLMN HLNE HLN HLP HLSO HLT HLX HMA HMAC HMAN HMC HMFAF HMG HMI HMLP HMMD HMN',
    'HMMR HMNY HMNX HMON HMST HMY HNI HNNA HNRG HNW HNZ HOG HOFT HOLI HOLX HOMB',
    'HOME HONE HOOD HOOK HOP HOPE HOPI HORI HOST HOTH HOUR HOUS HOVHP HOVN HOV HP',
    'HPA HPAI HPE HPF HPGSU HPJ HPK HPKEW HPP HPQ HPS HPTA HQH HQL HQT HQY HR HRB',
    'HRC HRDI HRI HRMY HRP HRPK HRTG HRTX HRX HRZN HSAQ HSBC HSCZ HSD HSDT HSG HSI',
    'HSIC HSII HSM HSON HST HSTA HSTM HSTN HSY HT HTA HTAB HTAQ HTBI HTC HTFC HTGC',
    'HTGM HTHIY HTH HTHT HTIA HTLD HTLF HTOO HTR HTZ HUA HUBB HUBG HUBS HUC HUDI',
    'HUM HUMA HUMP HUNT HUN HUP HURC HURN HUSA HUT HVT HWBK HWC HWCP HWEL HWII HWK',
    'HWKN HWM HWS HWU HXD HXL HY HYAC HYCM HYEM HYG HYGH HYI HYLB HYLD HYLN HYP',
    'HYPE HYPR HYSK HYTM HYW HYZD HZN HZO HZNP HZR HZSP I IAA IAC IACC IAE IAF IAG',
    'IAMF IAMX IANA IART IATN IAU IBCE IBCP IBD IBDN IBDO IBDP IBDQ IBDR IBDS IBDU',
    'IBET IBEX IBF IBH IBIO IBKR IBM IBN IBND IBOC IBP IBRN IBTA IBTI IBTJ IBTK',
    'IBTL IBTM IBTN IBTO IBTX IBUY ICAD ICBK ICCC ICCH ICDA ICFI ICG ICHR ICI ICL',
    'ICLK ICLR ICMB ICN ICS ICUI ICVX ID IDA IDAI IDAQ IDBA IDCC IDCCS IDEC IDEA',
    'IDEM IDES IDEX IDHI IDL IDLB IDN IDRA IDRV IDT IDTI IDTY IDU IDXX IDYA IE IEA',
    'IEAS IEC IEF IEFA IEFN IEI IEMG IEO IEP IEPR IEV IEX IEZ IF IFA IFBD IFFN IFG',
    'IFIT IFN IFRA IFRS IFRX IFS IFT IFTA IGAC IGAN IGC IGCC IGD IGE IGEB IGF IGIB',
    'IGIC IGLE IGLEW IGLG IGMS IGN IGR IGSB IGTA IGTR IGWT IGV IGZ IH IHC IHD IHG',
    'IHI IHIT IHP IHS IHTA IHTIP IHY IIDR III IIIV IINN IIPR IIVI IIVI IIN IJH IJJ',
    'IJK IJR IJS IJT IKT ILCG ILF ILMN ILPT ILU ILYB IM IMAB IMAC IMACW IMAX IMBI',
    'IMBT IMCC IMCM IMCR IMDS IMG IMGO IMGP IMKR IMKTA IMLP IMMR IMNM IMNN IMNTW',
    'IMOM IMOS IMPAW IMP IMPL IMPO IMPP IMPR IMRN IMRV IMTB IMTC IMTE IMTM IMTO',
    'IMTX IMUX IMVT IMXI IMXY INAQ INBK INBKL INBP INBT INBX INCM INCR INCY IND',
    'INDB INDA INDF INDL INDP INDS INDU INDY INEX INFA INFN INFO INFU INFY ING INGN',
    'INGR INGX INI INKM INNV INO INOD INOV INPX INRE INS INSG INSI INSM INSP INST',
    'INTA INTC INTE INTG INTR INTS INTT INTU INTZ INUV INVA INVE INVH INVO INVZ INW',
    'INZY IO IOCF IOOF IOOO IOO IOR IOSP IOTS IOV IOZ IP IPAR IPAY IPAX IPAY IPC',
    'IPCJ IPCR IPDN IPF IPFF IPGP IPH IPI IPKW IPLDP IPO IPOF IPOH IPOZ IPP IPREP',
    'IPRO IPSC IPV IPVA IPVF IPW IPWR IPWLK IQ IQI IQLT IQSM IQV IR IRBO IRBT IRC',
    'IRCP IRD IREN IRET IRF IRFC IRGO IRIX IRMD IROQ IROH IRS IRTC IRWD ISAA ISBC',
    'ISD ISDR ISDS ISEC ISEE ISG ISIG ISJA ISLK ISLO ISM ISMD ISMQ ISNS ISO ISPC',
    'ISPH ISR ISRA ISRG ISRL ISSC ISTR ISUB ISVL ISYB IT ITA ITAQ ITCB ITCI ITCH',
    'ITI ITIB ITNE ITP ITRG ITRN ITRW ITRU ITS ITT ITUB ITW ITWG IUS IUSB IUSG',
    'IUSV IUTX IVA IVAC IVAN IVC IVCB IVCP IVE IVENC IVENG IVES IVH IVLU IVO IVOG',
    'IVOL IVOO IVOV IVR IVT IVV IVVD IVVG IVW IVZ IVZO IW IWB IWD IWF IWL IWM IWN',
    'IWO IWP IWR IWS IWV IWX IWY IX IXC IXG IXJ IXN IXP IXSE IXUS IZEA IZM J JACK',
    'JAGX JAKK JAMF JAN JANX JAQC JAZZ JBG JBI JBK JBL JBLU JBN JBRA JBSS JBT JCAP',
    'JCE JCIC JCS JCSE JCT JCTCF JD JDIV JE JEF JELD JEM JEPI JEPQ JEQI JEQ JETS',
    'JFBR JFIN JFL JFR JFU JG JGLO JGR JGV JHB JHG JHI JHMA JHMB JHMC JHMD JHMF',
    'JHMH JHMI JHMM JHP JHQ JHS JHX JIB JIGGY JILL JIM JINX JIU JIVE JJSF JJU JK',
    'JKHY JKI JKS JLCO JLS JMC JMIA JMIN JMT JNJ JNPR JNUG JO JOB JOBY JOE JOFF',
    'JOG JOQQ JOUT JP JPAN JPED JPEF JPEM JPGE JPIN JPMC JPN JPS JPSE JPST JPTC',
    'JPUS JPXN JQC JQJ JQUA JRC JRNY JRVR JRXX JSAIY JSCP JSDA JSDA JSHG JSLN JSM',
    'JSMD JSML JSPR JT JTEK JTPY JUN JUNE JUPW JUV JVA JVAL JVL JW JWN JX JXJT JXN',
    'JYL JYM JZ JZRO JZXN K KA KACL KACLU KAIR KALA KALU KAMN KANE KAPA KAR KARO',
    'KARO KB KBAL KBC KBE KBH KBR KBWB KBWD KBWP KBWR KBWY KC KCAC KCCA KCCI KCD',
    'KCE KCGI KCNLF KCT KD KDMN KDNY KDP KDR KDT KDTW KE KEA KEJI KEK KEM KEN KEMP',
    'KENW KEP KEQU KERN KET KEX KEY KEYW KF KFFB KFIN KFN KFRC KFS KFY KGC KGEI',
    'KGFHF KHC KIDS KIG KIM KIN KINN KINZ KIOT KIRK KISS KIU KIX KJB KKK KKRS KKT',
    'KL KLAC KLAR KLAW KLCD KLIC KLNE KLTR KLXE KM KMB KMDA KMF KMI KMPB KMT KMX',
    'KN KNBE KNDI KNEY KNEXT KNGIS KNL KNOG KNOP KNOXF KNSL KNW KNX KO KODK KOF KOL',
    'KOLD KOMP KOP KOPN KORE KORP KOS KOSS KPAY KPBI KPLT KPLTW KPMX KPRX KPTI KR',
    'KRA KRC KRBP KRBN KREF KREG KRNL KRNLU KRNY KROS KROX KRP KRS KRTX KRUS KRY',
    'KSAV KSBI KSCM KSCP KSI KSM KSS KSST KSU KSY KT KTAM KTB KTCC KTF KTH KTOS',
    'KTRA KTTAY KTYB KUB KUE KUKE KULR KUO KURV KUSBU KVAC KVHI KVS KVSA KVSC KVY',
    'KW KWAC KWE KWEB KWR KX KXIN KXS KY KYCH KYE KYN KYND KYMR KYNC KYNDRX KYRN',
    'KYZ KZFS KZR KZRY L LAAA LAAB LAAC LAAD LAAM LAAO LAAP LAAQ LAAX LABU LAC LACQ',
    'LAD LADR LAES LAKE LALN LAMA LAMD LANC LAND LANV LARK LASI LASR LAT LATG LATH',
    'LATI LATN LAUR LAUT LAW LAX LAWS LAYN LAZR LAZY LB LBAI LBC LBCRW LBF LBMH LBRDA',
    'LBRDK LBRT LBSAX LBTYA LBTYB LBTYK LBY LC LCA LCAA LCAAU LCAHW LCB LCC LCDX LCEM',
    'LCG LCH LCID LCII LCMIX LCN LCNB LCOAX LCP LCPG LCR LCRX LCUD LCWA LD LDCA LDDD',
    'LDF LDHL LDNXF LDOS LDRS LDS LDTC LDW LDWY LE LEA LEAD LEAF LEAP LEAS LECO LEG',
    'LEGH LEGN LEGS LEJU LEIX LEN LEND LEO LEON LESL LET LETN LETPF LEU LEV LEVI',
    'LEXX LFAC LFCR LFG LFMD LFS LFST LFT LFTR LFUS LFWD LFW LGAC LGCL LGCY LGFC',
    'LGHL LGIH LGMK LGMS LGND LGO LGOV LGS LGSAX LGST LGSTW LGTV LGVN LGY LH LHCG',
    'LHGN LHDX LHN LHTZ LHX LI LIAF LIBI LIBY LIDR LIFE LIFIT LILA LILAK LILM LIM',
    'LIN LINC LIND LINVF LION LIOX LIQT LITB LITE LITH LITM LITP LITT LIV LIVE LIVN',
    'LIVX LIXT LIXTW LIXTX LIZI LJAQ LJIH LKCO LKEP LKES LKFN LKQ LKSD LKW LLAP LLG',
    'LLL LLLI LLNW LLY LLYVA LMACA LMAT LMB LMBO LMDA LMFA LMND LMO LMPAX LMPX LMRK',
    'LMRKO LMSIX LMT LMTX LN LNB LNC LNDC LNFA LNG LNKB LNN LNOT LNSR LNTH LNVGY',
    'LNW LO LOAN LOCB LOCO LOD LOF LOGC LOGI LOMA LOMO LONE LONG LONZ LOOP LOPE',
    'LOPP LOPX LORF LOT LOTA LOTS LOVE LOW LOXO LP LPA LPAA LPAL LPBB LPC LPG LPHL',
    'LPHX LPI LPLA LPP LPR LPRO LPSN LPTH LPTV LPTX LPX LQDA LQDB LQDF LQDI LQDT',
    'LQR LQTY LRE LREN LRGC LRGF LRGV LRHC LRN LRND LRNN LRTX LRVS LS LSAF LSAMX',
    'LSBK LSCC LSEA LSEG LSF LSG LSI LSGM LSPD LSPN LSPR LSR LSST LSTB LSTK LSTL',
    'LSTR LSTU LSV LSVIX LT LTAH LTBR LTC LTCH LTD LTH LTGC LTHR LTI LTIMF LTIZ',
    'LTL LTNC LTPZ LTRN LTRP LTRX LTRY LTS LTSA LTWR LU LUCD LUCK LULU LUMN LUNA',
    'LUNG LUV LUXAF LUXH LUXY LUZ LVAC LVAL LVGN LVH LVHD LVHI LVIP LVLU LVMH LVMUY',
    'LVS LVUS LVW LVWR LW LWEB LWLG LWPHY LWT LX LXEH LXP LXRX LXS LXU LYA LYBC',
    'LYCB LYCG LYCY LYEL LYG LYLT LYL LYN LYRA LYRAQ LYRI LYTS LYTT LYV LZB LZEN',
    'LZMH M MA MAA MAAQ MAATF MABA MAC MACC MACE MACK MACS MACX MADE MAER MAGA MAGE',
    'MAGI MAGIC MAGSF MAIN MAJR MAKEF MALA MALR MALT MAMA MAMO MAN MANA MANG MANI',
    'MANN MANT MANU MAR MARA MARC MARE MARG MARI MARK MARPS MARS MARTY MARV MAS MASI',
    'MASS MAST MASV MAT MATB MATE MATF MATH MATL MATN MATO MATS MATV MATW MATX MAURY',
    'MAV MAVA MAVIX MAWK MAX MAXN MAXR MAYS MBAC MBCN MBFC MBI MBIG MBIN MBINO MBIT',
    'MBK MBKE MBLY MBN MBNKP MBO MBOT MBOX MBSC MBSD MBSF MBSY MBTC MBUU MBWM MC',
    'MCAA MCACX MCAF MCAFR MCAGU MCB MCBC MCBS MCC MCDC MCDF MCDR MCEF MCELW MCG',
    'MCHB MCHI MCHP MCHX MCI MCIC MCK MCLDF MCLY MCMJ MCN MCO MCOM MCOR MCORQ MCP',
    'MCRI MCRIX MCR MCS MCSE MCV MCW MCX MCY MD MDAI MDALF MDBH MDC MDCO MDCP MDDI',
    'MDDSX MDES MDEX MDGL MDIA MDJH MDLZ MDMD MDN MDNA MDNC MDNR MDOG MDP MDRA MDRR',
    'MDRX MDS MDTX MDUAX MDVL MDWD MDWT MDXG MDXH MDY MDYG MDYV ME MEAN MEC MED MEDP',
    'MEDS MEG MEI MEIP MELI MELL MEMO MEN MENL MEP MERC MET META METC METE METH',
    'METV MEUA MEUC MEXX MF MFA MFAC MFAN MFAO MFAP MFAQ MFAS MFAX MFBC MFBJ MFBS',
    'MFC MFCR MFDX MFEM MFF MFG MFGD MFH MFHD MFI MFIC MFIN MFIV MFL MFLO MFM MFMS',
    'MFN MFNC MFNCR MFO MFON MFP MFRO MFS MFSC MFSF MFSP MFST MFTGX MFV MFX MGAM',
    'MGC MGCD MGEE MGEN MGFXF MGI MGIC MGLD MGLDY MGLW MGM MGMO MGMT MGNI MGNR MGNS',
    'MGNX MGOL MGP MGPI MGRC MGRO MGT MGTX MGU MGV MGY MHC MHD MHF MHH MHHNV MHI',
    'MHK MHLA MHLAX MHLD MHN MHO MHOAX MHTAY MHY MI MIAX MIBAX MIC MICT MID MIDD',
    'MIE MIEN MIFI MIG MIIV MIKE MILN MIND MINDS MINI MINM MINNF MINT MIO MIPA MIPL',
    'MIQ MIR MIRA MIRM MIRO MIST MIT MITK MITL MITN MITQ MITT MITU MIV MIXT MIVS',
    'MIVT MIXT MJ MJAC MJF MJIS MJNE MK MKC MKD MKE MKF MKGI MKL MKO MKRS MKSF',
    'MKTX MKTXF MKTY MKUL MKV MKXI ML MLAB MLAI MLAIX MLAX MLCO MLD MLDAX MLEC MLEG',
    'MLFB MLGO MLHR MLHC MLI MLIC MLIIF MLIN MLKN MLL MLLAX MLM MLNK MLNT MLP MLPO',
    'MLPR MLPX MLR MLRS MLSC MLSE MLSO MLSS MLT MLTI MLTL MLTR MLVF MM MMA MMAB',
    'MMAC MMAL MMAS MMAT MMBEF MMBN MMCA MMD MMEA MMEDF MMEX MMFN MMGN MMHS MMI MMIN',
    'MMIR MMIT MML MMLP MMM MMND MMNFF MMO MMOAX MMON MMP MMPIX MMPS MMRC MMRHF MMS',
    'MMSI MMTM MMT MMTLF MMTRS MMU MMV MMVWF MMVXX MMX MMYT MN MNAX MNC MNCPX MNDO',
    'MNDT MNE MNGA MNGN MNGR MNIN MNKD MNO MNOD MNOV MNP MNPR MNQ MNRL MNRO MNRTF',
    'MNSB MNSD MNSJ MNSO MNSP MNST MNT MNTK MNTN MNTS MNTV MNTX MNXMF MO MOB MOBBF',
    'MOBV MOCD MOD MODN MODV MOG MOGA MOGO MOHO MOI MOIN MOLN MOM MOMO MON MONA',
    'MONO MONS MONT MOO MOON MOOLV MOOS MOOV MOP MOPR MOR MORF MORG MORN MORR MOS',
    'MOSS MOST MOT MOTG MOTH MOTX MOTS MOV MOXC MOXF MOY MP MPA MPAA MPAC MPAD MPAI',
    'MPAQ MPAL MPAM MPAS MPAY MPB MPC MPCF MPCTF MPDV MPE MPF MPFMF MPGN MPHS MPHX',
    'MPII MPK MPKU MPL MPLX MPLN MPLO MPMQ MPN MPO MPOS MPR MPRA MPRT MPRW MPRX MPS',
    'MPSS MPSXX MPT MPTI MPTIX MPVD MPWB MPW MPWR MPWX MPX MPY MQ MQB MQLL MQP MQT',
    'MQY MR MRA MRAM MRAXX MRAZ MRB MRC MRCAY MRCC MRCI MRCP MRCY MRDB MRDI MRDS',
    'MRE MREE MREO MREQ MREV MRGE MRGR MRIN MRIO MRK MRKL MRKSF MRLA MRLN MRMD MRNA',
    'MRNJ MRNN MRNO MRNS MRO MROY MROZ MRP MRPG MRQI MRRS MRS MRSC MRSD MRSK MRSN',
    'MRTX MRUS MRUT MRVL MRVI MRVI MRX MRXS MRYN MRZ MS MSA MSAC MSACX MSAI MSAMW',
    'MSAS MSAWX MSB MSBI MSBM MSBR MSBT MSC MSCI MSCM MSCO MSCW MSD MSDI MSDIX MSE',
    'MSEA MSEB MSEC MSEED MSET MSEX MSF MSFAX MSFC MSFE MSFF MSFI MSFIX MSFT MSGE',
    'MSGM MSGO MSGS MSH MSHIX MSHPF MSI MSIA MSIF MSII MSIM MSIP MSJP MSJQ MSKE MSKU',
    'MSLP MSMA MSNR MSNVF MSNX MSO MSOF MSP MSPC MSPD MSPY MSRS MSRT MSSA MSSBX MSSE',
    'MSSS MSST MSSTX MST MSTB MSTC MSTI MSTL MSTO MSTR MSTX MSTW MSU MSUD MSUN MSUT',
    'MSUW MSVB MSVI MSVX MSW MSWI MSWN MSY MSYT MSYX MT MTA MTAC MTAI MTAL MTAN MTAP',
    'MTAQ MTAS MTAU MTAX MTB MTBA MTBL MTBP MTC MTCH MTCL MTCM MTCO MTCR MTCY MTD',
    'MTDI MTDR MTDRF MTE MTEAF MTECH MTEC MTEK MTEL MTEM MTEMP MTEN MTEP MTEXX MTF',
    'MTG MTGE MTH MTHD MTHRF MTK MTL MTLA MTLS MTLW MTM MTMV MTN MTNB MTNE MTNN',
    'MTOB MTP MTPL MTPP MTPR MTR MTRA MTRC MTRI MTRN MTRON MTRS MTRT MTRV MTRW MTRX',
    'MTRZ MTS MTSA MTSB MTSC MTSD MTSI MTSL MTSN MTSR MTSS MTST MTSU MTSW MTSZ MTT',
    'MTTE MTTI MTTP MTTW MTTY MTU MTUM MTUS MTV MTW MTX MTXR MTY MTZ MU MUBB MUBX',
    'MUFG MULN MULTI MUMS MUNI MUNN MURA MURP MUR MUSA MUSS MUST MUTE MUTI MUTN',
    'MUTR MUTS MUVT MUXU MUXT MUXY MUY MV MVA MVBF MVCAX MVC MVCDX MVEA MVEM MVEN',
    'MVEO MVEX MVF MVFU MVG MVGC MVGN MVGS MVHA MVHC MVI MVIO MVIOX MVIS MVL MVLU',
    'MVLW MVMA MVNA MVNR MVNT MVO MVPA MVPS MVRL MVRS MVRY MVS MVST MVTI MVTX MVV',
    'MVVI MW MWA MWB MWC MWCP MWD MWF MWG MWK MWLA MWMA MWNI MWO MWP MWRD MWS',
    'MWSAF MWTX MWV MX MXA MXC MXE MXEC MXF MXFC MXIM MXIX MXL MXMS MXNU MXP MXPE',
    'MXR MXROF MXRS MXSAF MXSB MXST MXT MXTEC MXV MXY MXZ MY MYC MYCC MYCO MYD MYFN',
    'MYG MYGO MYI MYIN MYKW MYL MYMD MYMO MYN MYND MYNT MYNZ MYOB MYOS MYOV MYPN',
    'MYPRE MYRG MYRS MYRREX MYSZ MYT MYTH MYV MYZED MZ MZA MZT NA NAA NAB NABR NACE',
    'NACP NACU NACW NAD NAFCX NAFX NAH NAII NAK NAL NALT NAM NAMR NAMS NANC NAND',
    'NANOF NANR NAPA NAPO NAPSF NAQ NAR NARA NARC NARI NARS NART NARZ NASA NASD NASGF',
    'NASN NAT NATH NATR NATS NATU NATY NAV NAVB NAVC NAVE NAVI NAVIX NAVM NAVR NAWS',
    'NAWX NAX NAYA NAYX NAZ NB NBA NBB NBC NBCE NBCP NBCY NBH NBHC NBII NBLX NBN',
    'NBO NBPE NBR NBRV NBS NBSC NBSE NBSFU NBSO NBST NBT NBTH NBTP NBTV NBTX NBUS',
    'NBV NBW NBX NBY NC NCA NCACF NCAF NCAQ NCAS NCATF NCAU NCAV NCAW NCB NCBC NCBK',
    'NCBS NCBX NCCC NCDA NCEA NCFM NCGM NCH NCHC NCHIV NCHL NCHLX NCI NCIF NCII',
    'NCIX NCK NCKL NCL NCLA NCLAF NCLAX NCLH NCLS NCLX NCM NCMD NCMI NCMO NCMPI',
    'NCMX NCN NCNA NCNB NCNC NCNO NCO NCP NCPA NCPI NCPL NCPM NCQ NCR NCRA NCRB',
    'NCRD NCRE NCRH NCRI NCRN NCRO NCRRP NCRT NCS NCSG NCSI NCSLT NCSM NCSO NCSP',
    'NCST NCSU NCTA NCTB NCTC NCTF NCTH NCTI NCTJF NCTL NCTM NCTN NCTO NCTP NCTQ',
    'NCTR NCTS NCTV NCTX NCTY NCU NCU NCUS NCV NCVC NCVF NCVI NCVIS NCVLY NCW NCX',
    'NCY NCYB NCYC NCYD NCYF NCYN NCYS NCYU NCYY NCYZ ND NDA NDAQ NDB NDBC NDBN',
    'NDBS NDC NDDFY NDE NDEFX NDEG NDEK NDEPT NDES NDEW NDF NDFC NDFS NDGR NDI NDK',
    'NDL NDLL NDLO NDM NDMO NDN NDNR NDO NDOP NDP NDPE NDPF NDQ NDRA NDRB NDRC',
    'NDRI NDRT NDS NDSC NDSF NDSN NDST NDSU NDSW NDTB NDU NDVA NDVB NDVLY NDVN NDVRS',
    'NDVT NDVW NDX NDXI NDXF NDXS NDY NDZ NE NEA NEAG NEAR NEB NEBC NEBO NECA NECC',
    'NECS NECT NEDD NEDL NEED NEEP NEER NEES NEEV NEFF NEGR NEGU NEIA NEII NEIR NEJN',
    'NEJO NEK NEKO NELA NELC NELG NELL NELO NELS NELU NELV NELX NELY NEMC NEMF NEMO',
    'NEMW NENA NENB NENL NENR NENT NEOC NEOE NEOG NEOL NEON NEOS NEOSX NEP NEPA NEPI',
    'NEPR NEPS NEPU NEQ NEQI NEQN NEQU NERD NERNF NERO NERT NERU NES NESC NESF NESM',
    'NESP NESS NESSP NEST NESTE NESTM NET NETC NETD NETG NETL NETO NETP NETPF NETR',
    'NETS NETT NETU NETV NETW NETWF NETX NETZ NEUB NEUE NEUG NEUQ NEUR NEUT NEUZF',
    'NEV NEVA NEVE NEVF NEVLF NEVM NEVMX NEVRO NEVS NEVT NEVV NEVX NEW NEWA NEWB',
    'NEWC NEWE NEWI NEWL NEWM NEWMF NEWN NEWO NEWP NEWR NEWS NEWT NEWW NEWX NEWY',
    'NEWZ NEX NEXA NEXB NEXCF NEXD NEXE NEXF NEXG NEXI NEXL NEXM NEXN NEXOF NEXR',
    'NEXS NEXT NEXU NEXV NEY NEYO NEYX NEYZ NF NFA NFAM NFAP NFAQ NFAS NFAT NFB',
    'NFBK NFBS NFC NFCA NFCC NFCI NFCM NFCO NFCP NFCX NFCY NFD NFDB NFDX NFE NFEC',
    'NFEI NFES NFEV NFEX NFF NFFI NFFN NFFO NFFX NFG NFGA NFGF NFGN NFGO NFH NFHG',
    'NFI NFIA NFIB NFIC NFID NFIE NFIF NFII NFIL NFIN NFIV NFIX NFJ NFJD NFJH NFJO',
    'NFK NFKC NFKR NFKU NFL NFLD NFLI NFLN NFLOP NFLX NFLY NFM NFMA NFMC NFME NFMO',
    'NFMS NFMW NFN NFNB NFNC NFNR NFNS NFNT NFO NFOAU NFOB NFOD NFOE NFOF NFOG NFOH',
    'NFOI NFOJ NFOK NFOL NFOM NFON NFOO NFOP NFOQ NFOR NFOS NFOT NFOU NFOV NFOW',
    'NFOX NFOY NFOZ NFP NFPE NFPL NFPM NFPO NFPP NFPR NFPS NFPT NFPU NFQ NFQN NFQR',
    'NFR NFRA NFRC NFRH NFRI NFRL NFRN NFRO NFRP NFRR NFRS NFRT NFRU NFRX NFRZ NFS',
    'NFSA NFSE NFSI NFSL NFSO NFSP NFSR NFSS NFST NFSU NFSV NFSY NFT NFTA NFTB NFTC',
    'NFTD NFTE NFTF NFTG NFTH NFTI NFTJ NFTK NFTL NFTM NFTN NFTO NFTP NFTQ NFTR',
    'NFTS NFTT NFTU NFTV NFTW NFTX NFTY NFTZ NFU NFUB NFUC NFUF NFUH NFUL NFUM',
    'NFUN NFUP NFUR NFUS NFUT NFUV NFUW NFUX NFUZ NFV NFVA NFVB NFVC NFVD NFVE',
    'NFVF NFVG NFVH NFVI NFVJ NFVK NFVL NFVM NFVN NFVO NFVP NFVQ NFVR NFVS NFVT',
    'NFVU NFVV NFVW NFVX NFVY NFVZ NFW NFWA NFWB NFWC NFWD NFWE NFWF NFWG NFWH',
    'NFWI NFWJ NFWK NFWL NFWM NFWN NFWO NFWP NFWQ NFWR NFWS NFWT NFWU NFWV NFWW',
    'NFWX NFWY NFWZ NFX NFXA NFXB NFXC NFXD NFXE NFXF NFXG NFXH NFXI NFXJ NFXK',
    'NFXL NFXM NFXN NFXO NFXP NFXQ NFXR NFXS NFXT NFXU NFXV NFXW NFXX NFXY NFXZ',
    'NFY NFYA NFYB NFYC NFYD NFYE NFYF NFYG NFYH NFYI NFYJ NFYK NFYL NFYM NFYN',
    'NFYO NFYP NFYQ NFYR NFYS NFYT NFYU NFYV NFYW NFYX NFYY NFYZ NFZ NFZA NFZB',
    'NFZC NFZD NFZE NFZF NFZG NFZH NFZI NFZJ NFZK NFZL NFZM NFZN NFZO NFZP NFZQ',
    'NFZR NFZS NFZT NFZU NFZV NFZW NFZX NFZY NFZZ NG NGA NGAC NGAM NGAU NGBC NGCA',
    'NGD NGE NGEN NGHC NGIC NGIO NGK NGL NGLD NGLS NGM NGMC NGMS NGNE NGO NGNE NGS',
    'NGSC NGSP NGV NGVC NGVT NGX NH NHC NHEP NHF NHI NHIC NHK NHO NHRO NI NICE',
    'NICK NID NIFE NIG NIHD NII NILE NIM NINE NIO NIOB NIPN NIRA NIRM NIRO NIRI',
    'NISA NIST NITEX NITO NIU NIV NIX NJR NK NKA NKBA NKLA NKO NKSH NKTR NKT NL',
    'NLDX NLFC NLGN NLIC NLIP NLKA NLNK NLO NLP NLPO NLPX NLR NLRP NLRR NLRS NLRT',
    'NLS NLSN NLSO NLSP NLT NLTA NLU NLV NLW NLWX NLY NM NMAW NMB NMC NMCA NMD',
    'NMFC NMFG NMGN NMI NMIC NMIH NMK NML NMM NMMC NMN NMO NMON NMP NMPE NMPH NMR',
    'NMRA NMRD NMRK NMRR NMS NMSO NMSP NMST NMT NMTA NMTC NMTK NMTR NMUC NMUX NMV',
    'NMW NMY NMZ NN NNA NNAM NNAS NNBR NNC NNCM NND NNDI NNE NNFT NNG NNGY NNI',
    'NNK NNMI NNN NNND NNNG NNO NNOAC NNP NNPA NNR NNS NNSO NNST NNT NNW NNY NNZYX',
    'NO NOA NOAH NOC NODK NOG NOK NOKPF NOM NOMD NOMI NOP NOR NORA NORD NORG NORIS',
    'NORM NOSE NOTE NOV NOVA NOVAU NOVAV NOVB NOVHF NOVO NOVR NOVS NOVT NOW NOWG',
    'NOX NPA NPAB NPAC NPACW NPAL NPAM NPAO NPAS NPAT NPAU NPAV NPBZ NPC NPCE NPCOW',
    'NPCT NPCV NPCY NPE NPEP NPEX NPFF NPG NPGM NPHI NPIFF NPIS NPK NPKI NPL NPLX',
    'NPN NPNY NPO NPPA NPPC NPPL NPPS NPRA NPR NPRE NPRMF NPRS NPRST NPRT NPS NPSA',
    'NPSC NPSD NPSE NPSF NPSGF NPSH NPSI NPSJ NPSK NPSL NPSM NPSO NPSP NPSQ NPSR',
    'NPSS NPST NPSU NPSV NPSW NPSX NPSY NPSZ NPT NPTA NPTB NPTC NPTD NPTE NPTF',
    'NPTG NPTH NPTI NPTJ NPTK NPTL NPTM NPTN NPTO NPTP NPTQ NPTR NPTS NPTT NPTU',
    'NPTV NPTW NPTX NPTY NPTZ NPU NPUA NPUB NPUC NPUD NPUE NPUF NPUG NPUH NPUI',
    'NPUJ NPUK NPUL NPUM NPUN NPUO NPUP NPUQ NPUR NPUS NPUT NPUU NPUV NPUW NPUX',
    'NPUY NPUZ NPV NPVA NPVB NPVC NPVD NPVE NPVF NPVG NPVH NPVI NPVJ NPVK NPVL',
    'NPVM NPVN NPVO NPVP NPVQ NPVR NPVS NPVT NPVU NPVV NPVW NPVX NPVY NPVZ NPW',
    'NPWA NPWB NPWC NPWD NPWE NPWF NPWG NPWH NPWI NPWJ NPWK NPWL NPWM NPWN NPWO',
    'NPWP NPWQ NPWR NPWS NPWT NPWU NPWV NPWW NPWX NPWY NPWZ NPX NPXA NPXB NPXC',
    'NPXD NPXE NPXF NPXG NPXH NPXI NPXJ NPXK NPXL NPXM NPXN NPXO NPXP NPXQ NPXR',
    'NPXS NPXT NPXU NPXV NPXW NPXX NPXY NPXZ NPY NPYA NPYB NPYC NPYD NPYE NPYF',
    'NPYG NPYH NPYI NPYJ NPYK NPYL NPYM NPYN NPYO NPYP NPYQ NPYR NPYS NPYT NPYU',
    'NPYV NPYW NPYX NPYY NPYZ NPZ NPZA NPZB NPZC NPZD NPZE NPZF NPZG NPZH NPZI',
    'NPZJ NPZK NPZL NPZM NPZN NPZO NPZP NPZQ NPZR NPZS NPZT NPZU NPZV NPZW NPZX',
    'NPZY NPZZ NQ NQA NQAC NQAU NQAV NQAW NQAX NQB NQBA NQBB NQBC NQBD NQBE NQBF',
    'NQBG NQBH NQBI NQBJ NQBK NQBL NQBM NQBN NQBO NQBP NQBQ NQBR NQBS NQBT NQBU',
    'NQBV NQBW NQBX NQBY NQBZ NQC NQCA NQCB NQCC NQCD NQCE NQCF NQCG NQCH NQCI',
    'NQCJ NQCK NQCL NQCM NQCN NQCO NQCP NQCQ NQCR NQCS NQCT NQCU NQCV NQCW NQCX',
    'NQCY NQCZ NQD NQDA NQDB NQDC NQDD NQDE NQDF NQDG NQDH NQDI NQDJ NQDK NQDL',
    'NQDM NQDN NQDO NQDP NQDQ NQDR NQDS NQDT NQDU NQDV NQDW NQDX NQDY NQDZ NQE',
    'NQEA NQEB NQEC NQED NQEE NQEF NQEG NQEH NQEI NQEJ NQEK NQEL NQEM NQEN NQEO',
    'NQEP NQEQ NQER NQES NQET NQEU NQEV NQEW NQEX NQEY NQEZ NQF NQFA NQFB NQFC',
    'NQFD NQFE NQFF NQFG NQFH NQFI NQFJ NQFK NQFL NQFM NQFN NQFO NQFP NQFQ NQFR',
    'NQFS NQFT NQFU NQFV NQFW NQFX NQFY NQFZ NQG NQGA NQGB NQGC NQGD NQGE NQGF',
    'NQGG NQGH NQGI NQGJ NQGK NQGL NQGM NQGN NQGO NQGP NQGQ NQGR NQGS NQGT NQGU',
    'NQGV NQGW NQGX NQGY NQGZ NQH NQHA NQHB NQHC NQHD NQHE NQHF NQHG NQHH NQHI',
    'NQHJ NQHK NQHL NQHM NQHN NQHO NQHP NQHQ NQHR NQHS NQHT NQHU NQHV NQHW NQHX',
    'NQHY NQHZ NQI NQIA NQIB NQIC NQID NQIE NQIF NQIG NQIH NQII NQIJ NQIK NQIL',
    'NQIM NQIN NQIO NQIP NQIQ NQIR NQIS NQIT NQIU NQIV NQIW NQIX NQIY NQIZ NQJ',
    'NQJA NQJB NQJC NQJD NQJE NQJF NQJG NQJH NQJI NQJJ NQJK NQJL NQJM NQJN NQJO',
    'NQJP NQJQ NQJR NQJS NQJT NQJU NQJV NQJW NQJX NQJY NQJZ NQK NQKA NQKB NQKC',
    'NQKD NQKE NQKF NQKG NQKH NQKI NQKJ NQKK NQKL NQKM NQKN NQKO NQKP NQKQ NQKR',
    'NQKS NQKT NQKU NQKV NQKW NQKX NQKY NQKZ NQL NQLA NQLB NQLC NQLD NQLE NQLF',
    'NQLG NQLH NQLI NQLJ NQLK NQLL NQLM NQLN NQLO NQLP NQLQ NQLR NQLS NQLT NQLU',
    'NQLV NQLW NQLX NQLY NQLZ NQM NQMA NQMB NQMC NQMD NQME NQMF NQMG NQMH NQMI',
    'NQMJ NQMK NQML NQMM NQMN NQMO NQMP NQMQ NQMR NQMS NQMT NQMU NQMV NQMW NQMX',
    'NQMY NQMZ NQN NQNA NQNB NQNC NQND NQNE NQNF NQNG NQNH NQNI NQNJ NQNK NQNL',
    'NQNM NQNN NQNO NQNP NQNQ NQNR NQNS NQNT NQNU NQNV NQNW NQNX NQNY NQNZ NQO',
    'NQOA NQOB NQOC NQOD NQOE NQOF NQOG NQOH NQOI NQOJ NQOK NQOL NQOM NQON NQOO',
    'NQOP NQOQ NQOR NQOS NQOT NQOU NQOV NQOW NQOX NQOY NQOZ NQP NQPA NQPB NQPC',
    'NQPD NQPE NQPF NQPG NQPH NQPI NQPJ NQPK NQPL NQPM NQPN NQPO NQPP NQPQ NQPR',
    'NQPS NQPT NQPU NQPV NQPW NQPX NQPY NQPZ NQQ NQQA NQQB NQQC NQQD NQQE NQQF',
    'NQQG NQQH NQQI NQQJ NQQK NQQL NQQM NQQN NQQO NQQP NQQQ NQQR NQQS NQQT NQQU',
    'NQQV NQQW NQQX NQQY NQQZ NQR NQRA NQRB NQRC NQRD NQRE NQRF NQRG NQRH NQRI',
    'NQRJ NQRK NQRL NQRM NQRN NQRO NQRP NQRQ NQRR NQRS NQRT NQRU NQRV NQRW NQRX',
    'NQRY NQRZ NQS NQSA NQSB NQSC NQSD NQSE NQSF NQSG NQSH NQSI NQSJ NQSK NQSL',
    'NQSM NQSN NQSO NQSP NQSQ NQSR NQSS NQST NQSU NQSV NQSW NQSX NQSY NQSZ NQT',
    'NQTA NQTB NQTC NQTD NQTE NQTF NQTG NQTH NQTI NQTJ NQTK NQTL NQTM NQTN NQTO',
]

def fetch_batch(symbols, session, start, end):
    """Fetch a batch of symbols in one request"""
    params = {
        'symbols': ','.join(symbols),
        'start': start.strftime('%Y-%m-%dT%H:%M:%SZ'),
        'end': end.strftime('%Y-%m-%dT%H:%M:%SZ'),
        'timeframe': '1Day',
        'adjustment': 'all',
        'limit': 10000,
        'feed': 'iex'
    }
    try:
        resp = session.get(f'{ALPACA_DATA_URL}/v2/stocks/bars', headers=HEADERS, params=params, timeout=60)
        return resp.json().get('bars', {})
    except:
        return {}

def extract_features_vectorized(df, symbol):
    """Vectorized feature extraction - much faster than row-by-row"""
    if len(df) < 90:
        return []
    
    close = df['close'].values.astype(float)
    high = df['high'].values.astype(float)
    low = df['low'].values.astype(float)
    volume = df['volume'].values.astype(float)
    open_p = df['open'].values.astype(float) if 'open' in df.columns else close
    
    samples = []
    indices = list(range(60, len(df) - 30, 15))
    
    for idx in indices:
        if close[idx] <= 0:
            continue
        
        max_gain = (np.max(high[idx:idx+30]) - close[idx]) / close[idx]
        
        window_close = close[idx-60:idx+1]
        window_high = high[idx-60:idx+1]
        window_low = low[idx-60:idx+1]
        window_vol = volume[idx-60:idx+1]
        window_open = open_p[idx-60:idx+1]
        
        returns = np.diff(window_close) / (window_close[:-1] + 0.001)
        
        f = {}
        for p in [5, 10, 20, 50]:
            f[f'sma_{p}'] = np.mean(window_close[-p:])
            f[f'vol_sma_{p}'] = np.mean(window_vol[-p:])
        
        for p in [5, 10, 20, 30]:
            f[f'volatility_{p}'] = np.std(returns[-p:]) if len(returns) >= p else np.std(returns)
        
        f['vol_compression_5_20'] = f['volatility_5'] / (f['volatility_20'] + 0.001)
        f['vol_compression_10_30'] = f['volatility_10'] / (f['volatility_30'] + 0.001)
        f['vol_compression_5_30'] = f['volatility_5'] / (f['volatility_30'] + 0.001)
        
        for p in [3, 5, 10, 20]:
            f[f'momentum_{p}'] = (window_close[-1] - window_close[-p-1]) / (window_close[-p-1] + 0.001)
        
        f['mom_acceleration'] = f['momentum_3'] - f['momentum_5']
        f['mom_inflection'] = f['momentum_5'] - f['momentum_10']
        
        for p in [5, 10, 20]:
            f[f'vol_ratio_{p}'] = np.mean(window_vol[-3:]) / (np.mean(window_vol[-p:]) + 1)
        
        f['vol_dryup_ratio'] = np.mean(window_vol[-5:]) / (np.mean(window_vol[-20:]) + 1)
        
        for p in [10, 20, 50]:
            f[f'price_vs_sma_{p}'] = window_close[-1] / (f[f'sma_{p}'] + 0.001)
        
        f['sma_slope_5_10'] = (f['sma_5'] - f['sma_10']) / (f['sma_10'] + 0.001)
        f['sma_slope_10_20'] = (f['sma_10'] - f['sma_20']) / (f['sma_20'] + 0.001)
        f['sma_slope_20_50'] = (f['sma_20'] - f['sma_50']) / (f['sma_50'] + 0.001)
        
        for p in [10, 20, 30]:
            f[f'range_{p}'] = (np.max(window_high[-p:]) - np.min(window_low[-p:])) / (window_close[-1] + 0.001)
        
        f['high_52w'] = np.max(high[max(0, idx-252):idx])
        f['breakout_proximity_52w'] = window_close[-1] / (f['high_52w'] + 0.001)
        
        for i in range(1, 6):
            gap = (window_open[-i] - window_close[-i-1]) / (window_close[-i-1] + 0.001)
            f[f'gap_day_{i}'] = gap
        
        dr = window_high[-10:] - window_low[-10:]
        cp = (window_close[-10:] - window_low[-10:]) / (dr + 0.001)
        f['close_position_avg'] = np.mean(cp)
        
        gains = returns[-14:].copy()
        gains[gains < 0] = 0
        losses = -returns[-14:].copy()
        losses[losses < 0] = 0
        f['rsi_14'] = 100 - (100 / (1 + np.mean(gains) / (np.mean(losses) + 0.0001)))
        
        atr_vals = [max(window_high[j] - window_low[j], abs(window_high[j] - window_close[j-1]), abs(window_low[j] - window_close[j-1])) for j in range(-14, 0)]
        f['atr_14'] = np.mean(atr_vals) / (window_close[-1] + 0.001)
        
        bb_sma, bb_std = np.mean(window_close[-20:]), np.std(window_close[-20:])
        f['bb_position'] = (window_close[-1] - bb_sma) / (2 * bb_std + 0.001)
        f['bb_width'] = (4 * bb_std) / (bb_sma + 0.001)
        
        f['current_price'] = window_close[-1]
        f['is_penny'] = 1.0 if window_close[-1] < 5 else 0.0
        
        sym_hash = int(hashlib.md5(symbol.encode()).hexdigest()[:8], 16) / (16**8)
        f['symbol_hash'] = sym_hash
        
        f = {k: float(v) if np.isfinite(v) else 0.0 for k, v in f.items()}
        f['symbol'] = symbol
        f['label'] = 1 if max_gain >= 0.50 else 0
        f['max_gain'] = max_gain
        
        samples.append(f)
    
    return samples

def process_parquet(path):
    """Process a single parquet file"""
    symbol = path.stem
    try:
        df = pd.read_parquet(path)
        return extract_features_vectorized(df, symbol)
    except:
        return []

def main():
    print("="*60)
    print("TURBO EXPAND - Efficient Stock Universe Expansion")
    print("="*60)
    
    existing = {p.stem for p in CACHE_DIR.glob('*.parquet')}
    print(f"Currently have: {len(existing)} stocks")
    
    all_symbols = set()
    for pool in SYMBOL_POOLS:
        for s in pool.split():
            if len(s) <= 5 and '.' not in s:
                all_symbols.add(s)
    
    new_symbols = [s for s in all_symbols if s not in existing]
    print(f"New symbols to fetch: {len(new_symbols)}")
    
    if new_symbols:
        print("\n[1/3] FETCHING NEW STOCKS (100 per batch)...")
        session = requests.Session()
        end = datetime.now()
        start = end - timedelta(days=3*365)
        
        saved = 0
        batch_size = 100
        
        for i in range(0, len(new_symbols), batch_size):
            batch = new_symbols[i:i+batch_size]
            bars = fetch_batch(batch, session, start, end)
            
            for sym, data in bars.items():
                if len(data) >= 90:
                    df = pd.DataFrame([{
                        'timestamp': x['t'],
                        'open': float(x['o']),
                        'high': float(x['h']),
                        'low': float(x['l']),
                        'close': float(x['c']),
                        'volume': float(x['v'])
                    } for x in data])
                    df = df.sort_values('timestamp').reset_index(drop=True)
                    df.to_parquet(CACHE_DIR / f'{sym}.parquet', index=False)
                    saved += 1
            
            print(f"  Batch {i//batch_size + 1}/{(len(new_symbols) + batch_size - 1)//batch_size}: +{saved} stocks")
            time.sleep(0.05)
        
        print(f"  Total new stocks saved: {saved}")
    
    print("\n[2/3] PARALLEL FEATURE EXTRACTION (8 workers)...")
    parquet_files = list(CACHE_DIR.glob('*.parquet'))
    print(f"  Processing {len(parquet_files)} stock files...")
    
    all_samples = []
    with ThreadPoolExecutor(max_workers=8) as executor:
        futures = {executor.submit(process_parquet, p): p for p in parquet_files}
        done = 0
        for future in as_completed(futures):
            samples = future.result()
            if samples:
                pos = [s for s in samples if s['label'] == 1]
                neg = [s for s in samples if s['label'] == 0 and s['max_gain'] < 0.15]
                
                np.random.seed(hash(futures[future].stem) % (2**32))
                if len(pos) > 20:
                    pos = [pos[j] for j in np.random.choice(len(pos), 20, replace=False)]
                if len(neg) > 40:
                    neg = [neg[j] for j in np.random.choice(len(neg), 40, replace=False)]
                
                all_samples.extend(pos + neg)
            
            done += 1
            if done % 200 == 0:
                print(f"    Processed {done}/{len(parquet_files)} files...")
    
    pos_count = sum(1 for s in all_samples if s['label'] == 1)
    print(f"  Total samples: {len(all_samples)} ({pos_count} moonshots)")
    
    print("\n[3/3] TRAINING MODEL...")
    feature_cols = sorted([k for k in all_samples[0].keys() if k not in ['symbol', 'label', 'max_gain']])
    
    symbols = list(set(s['symbol'] for s in all_samples))
    np.random.seed(42)
    np.random.shuffle(symbols)
    train_symbols = set(symbols[:int(len(symbols) * 0.7)])
    
    train = [s for s in all_samples if s['symbol'] in train_symbols]
    test = [s for s in all_samples if s['symbol'] not in train_symbols]
    
    X_train = np.array([[s.get(k, 0) for k in feature_cols] for s in train])
    y_train = np.array([s['label'] for s in train])
    X_test = np.array([[s.get(k, 0) for k in feature_cols] for s in test])
    y_test = np.array([s['label'] for s in test])
    
    print(f"  Train: {len(X_train)} ({sum(y_train)} pos) | Test: {len(X_test)} ({sum(y_test)} pos)")
    
    model = lgb.LGBMClassifier(
        n_estimators=300, max_depth=7, learning_rate=0.05, num_leaves=40,
        min_child_samples=20, subsample=0.8, colsample_bytree=0.8,
        scale_pos_weight=len(y_train[y_train == 0]) / (len(y_train[y_train == 1]) + 1),
        random_state=42, verbosity=-1, n_jobs=-1
    )
    model.fit(X_train, y_train)
    
    y_prob = model.predict_proba(X_test)[:, 1]
    prec = precision_score(y_test, (y_prob >= 0.5).astype(int), zero_division=0)
    rec = recall_score(y_test, (y_prob >= 0.5).astype(int), zero_division=0)
    auc = roc_auc_score(y_test, y_prob)
    
    print("\n" + "="*60)
    print(f"RESULTS ({len(symbols)} STOCKS)")
    print("="*60)
    print(f"  Precision: {prec:.1%} | Recall: {rec:.1%} | ROC-AUC: {auc:.3f}")
    
    for t in [0.6, 0.7, 0.8]:
        y_pred_t = (y_prob >= t).astype(int)
        print(f"  @ {t:.0%}: Precision {precision_score(y_test, y_pred_t, zero_division=0):.1%}, Recall {recall_score(y_test, y_pred_t, zero_division=0):.1%}")
    
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    with gzip.open(MODELS_DIR / 'moonshot_incremental_v2.pkl.gz', 'wb') as f:
        pickle.dump({
            'model': model,
            'feature_names': feature_cols,
            'version': f'4.0-{len(symbols)}stocks',
            'timestamp': datetime.now().isoformat(),
            'stocks_count': len(symbols),
            'samples_count': len(all_samples),
            'precision': float(prec),
            'recall': float(rec),
            'roc_auc': float(auc)
        }, f)
    
    print(f"\nModel saved: {len(symbols)} stocks, {len(all_samples)} samples")
    print(f"Total stocks in universe: {len(list(CACHE_DIR.glob('*.parquet')))}")

if __name__ == '__main__':
    main()
